from __future__ import annotations


def build_ultra_low_latency_cmd(ffmpeg_bin: str, input_url: str, rtmp_url: str) -> list[str]:
    return [
        ffmpeg_bin,
        "-re",
        "-fflags",
        "nobuffer",
        "-flags",
        "low_delay",
        "-strict",
        "experimental",
        "-probesize",
        "32",
        "-analyzeduration",
        "0",
        "-thread_queue_size",
        "1024",
        "-i",
        input_url,
        "-map",
        "0:a:0",
        "-vn",
        "-c:a",
        "aac",
        "-b:a",
        "128k",
        "-ar",
        "48000",
        "-ac",
        "2",
        "-af",
        "aresample=async=1:min_hard_comp=0.1:first_pts=0",
        "-flush_packets",
        "1",
        "-max_delay",
        "0",
        "-f",
        "flv",
        rtmp_url,
    ]
